#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
sudo apt upgrade
#clonwoking repo
git clone -b NoMulti https://github.com/RainBowCreation/autoscale.git
#install java
cd autoscale
set JAVA_OPTS="-Xms128m -Xmx4G"
chmod +x ./setup-debian.sh
sudo ./setup-debian.sh
