#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
cd 
#clonwoking repo
git clone https://github.com/RainBowCreation/autoscale.git
cd autoscale
chmod +x ./load_config.sh
sudo ./load_config.sh
chmod +x ./setup.sh
sudo ./setup.sh
# override config by "export config=value"