#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
cd 
export YUM=true

#clonwoking repo
git clone https://github.com/RainBowCreation/autoscale.git
cd autoscale

export CONFIG_FILE="config.json"

export CONFIG_FILE=config.json
eval "$("./load_config.sh")"

# override config by "export config=value" example
# export MASTER_ADDRESS="localhost:35353"

chmod +x ./setup.sh
sudo ./setup.sh

# override config by "export config=value"