#!/bin/bash
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
cd lib
chmod +x install.sh
./install.sh
cd ..
cd node
#download multipapernode 1.19.2-37
chmod +x install.sh
./install.sh
#set master node ip here
MULTIPAPER_MASTER_ADDRESS=3.86.190.46:35353
#startup server
chmod +x start.sh
./start.sh
