#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
sudo yum upgrade
#install java
sudo yum install jdk-20-headless
#install git
sudo yum install git -y
cd /home/ec2-user
#clonwoking repo
git clone https://github.com/RainBowCreation/wokernode.git
cd worknode/node
wget https://multipaper.io/api/v2/projects/multipaper/versions/1.19.2/builds/37/downloads/multipaper-1.19.2-37.jar
#startup server
./run.sh
